// Generated by unRap v1.06 by Kegetys

class CfgMovesMaleSdr : CfgMovesBasic {
	class States {
		class Crew;	// External class reference
		
		class sns_nekafcargo : Crew {
			file = "\sns_vehicles\anims\nekaf_driver.rtm";
			connectTo[] = {"Static_Dead", 1};
			leftHandIKBeg = true;
			leftHandIKCurve[] = {1};
			leftHandIKEnd = true;
			rightHandIKCurve[] = {1};
			righHandIKBeg = 1;
			righHandIKEnd = 1;
		};
		
		class sns_nekafcargoDT : Crew {
			file = "\sns_vehicles\anims\nekaf_driver.rtm";
			connectTo[] = {"Static_Dead", 1};
			leftHandIKBeg = true;
			leftHandIKCurve[] = {1};
			leftHandIKEnd = true;
			rightHandIKCurve[] = {1};
			righHandIKBeg = 1;
			righHandIKEnd = 1;
		};
		
		class sns_nekafdriver : Crew {
			file = "\sns_vehicles\anims\nekaf_driver.rtm";
			connectTo[] = {"Static_Dead", 1};
			leftHandIKBeg = true;
			leftHandIKCurve[] = {1};
			leftHandIKEnd = true;
			rightHandIKCurve[] = {1};
			righHandIKBeg = 1;
			righHandIKEnd = 1;
		};
	};
};
