// Generated by unRap v1.06 by Kegetys

class CfgMovesBasic {
	class DefaultDie;	// External class reference
	
	class ManActions {
		sns_nekafcargo = "sns_nekafcargo";
		sns_nekafcargoDT = "sns_nekafcargoDT";
		sns_nekafdriver = "sns_nekafdriver";
	};
};
