// Generated by unRap v1.06 by Kegetys

class CfgCloudlets {
	class ObjectDestructionFire1;	// External class reference
	
	class CarDestructionFire1 : ObjectDestructionFire1 {
		size[] = {"0.4 * intensity + 0.6", "0.1 * intensity + 0.1"};
		angleVar = 0.1;
		lifeTime = 1.3;
		rotationVelocityVar = 0;
	};
	class ObjectDestructionFire2;	// External class reference
	
	class CarDestructionFire2 : ObjectDestructionFire2 {
		size[] = {"0.4 * intensity + 0.6", 0.1};
		angleVar = 0.1;
		lifeTime = 1.3;
		rotationVelocityVar = 0;
	};
};
