// Generated by unRap v1.06 by Kegetys

class CfgNonAIVehicles {
	class ProxyFlag;	// External class reference
	class ProxyWeapon;	// External class reference
	
	class ProxyFlag_Auto : ProxyFlag {
		model = "\A3\data_f\proxies\Flags\FLAG_auto";
	};
	
	class ProxyFlag_Alone : ProxyFlag {
		model = "\A3\data_f\proxies\Flags\FLAG_alone";
	};
};
